export const environment = {
  environment: 'dev',
  production: false,
  Url: 'https://lyon.pagatodo360.net:88',
  URLRecibo: 'https://lyon.pagatodo360.net:3000',
  URLService: 'https://lyon.pagatodo360.net:4000',
  grant_type: 'password',
  refresh: 'refresh_token',
  client_id: 'jwtclientC0br4nz@PGT360',
  client_secret: 'secretkeyC0br4nz@PGT360',
  URLcyber: 'https://testsecureacceptance.cybersource.com/silent/pay',
  URLbnb: 'https://lyon.pagatodo360.net:4001/apiqr/v1',
  URLsocket: 'https://lyon.pagatodo360.net:88',
  IDKiosco: 'https://lyon.pagatodo360.net:4005',
  UrlPos: 'http://localhost:4701',
  usuarioPos: 'kiosco',
  passowordPos: '12345',
};
